### ISSUE TITLE
Game Performance Degradation Over Time

### ISSUE THREAD

**Issue by TKanX** [tridecco/game-client-web#22]
### Description:

The game experiences significant performance issues during gameplay. Initially, the game runs smoothly, but after approximately the 10th turn, it begins to lag and eventually becomes unresponsive. The memory usage remains stable at around 100MB, so memory leakage is not suspected. The issue seems to be related to the rendering logic using the Canvas API.

### Steps to Reproduce:

1. Start a new game session.
2. Play through approximately 10 turns.
3. Observe the increasing lag and eventual freezing of the game.

### Expected Behavior: 

The game should maintain consistent performance throughout all turns, without noticeable lag or freezing.

### Actual Behavior:

Performance deteriorates after several turns, leading to significant lag and eventual page unresponsiveness.

### Possible Causes:

- Inefficient or excessive Canvas redraws.
- Accumulation of event listeners or timers.
- Object creation without proper cleanup or reuse.
- Other potential causes related to rendering optimization.

**Comment by TKanX** [comment]
### Performance Recording Completed

I have completed a performance recording to analyze the issues with game performance. The recording includes details on where the performance degrades and potential bottlenecks.

![image](https://github.com/user-attachments/assets/ad488c2e-be42-4259-b245-ba95d1aeea01)

**Timeline Spikes:** Look for any sudden spikes in activity on the timeline that might indicate performance issues.
**Frame Rate:** Check the frame rate graph to see if there are significant drops.
**Main Thread Analysis:** Review the main thread’s activities to identify any long tasks or inefficient operations.
**Rendering Issues:** Analyze the rendering section for frequent or excessive painting operations.
**Memory Usage:** Observe memory usage patterns to ensure there are no unexpected increases.

### Performance Recording:

[Trace-20240831T115350.zip](https://github.com/user-attachments/files/16825741/Trace-20240831T115350.zip)

@tedhyu

**Comment by TKanX** [comment]
### Performance Recording Completed

I have completed a performance recording to analyze the issues with game performance. The recording includes details on where the performance degrades and potential bottlenecks.

![Screenshot 2024-08-31 124159](https://github.com/user-attachments/assets/e5aaaa9f-5cc7-4388-8dd7-35877647d422)

**Timeline Spikes:** Look for any sudden spikes in activity on the timeline that might indicate performance issues.
**Frame Rate:** Check the frame rate graph to see if there are significant drops.
**Main Thread Analysis:** Review the main thread’s activities to identify any long tasks or inefficient operations.
**Rendering Issues:** Analyze the rendering section for frequent or excessive painting operations.
**Memory Usage:** Observe memory usage patterns to ensure there are no unexpected increases.

@tedhyu

**Comment by tedhyu** [comment]
Very impressive, Tony.

**Comment by TKanX** [comment]
### Performance Analysis Update

![image](https://github.com/user-attachments/assets/169b4b58-86c6-4b8f-b4e0-94c2ecd61ad2)

I have recorded the performance data during the occurrence of the lagging issue. Here’s a summary of my findings:

Upon examining the first critical time frame where the game begins to experience severe lag, the following key observations were made:

![image](https://github.com/user-attachments/assets/3b3643ff-e263-47e9-9a3d-58d96855ea56)

1. Frame Rate Drop and Freeze:

The frame rate starts to drop sharply just before the game completely freezes. At this point, the frame rate data disappears from the timeline, indicating a total halt in the rendering process.

![image](https://github.com/user-attachments/assets/51d5f861-2345-423d-beb5-63929246540f)

Normal frame rate:

![image](https://github.com/user-attachments/assets/da041c23-4e8c-4d32-a56f-84feb09f9990)

Drop frame rate:

![image](https://github.com/user-attachments/assets/b3045e18-330b-4b52-aa13-315ffa848571)

2. GPU Activity:

Multiple GPU tasks, each taking approximately 751ms, were identified during the problematic frame. The green blocks on the timeline represent these GPU operations, indicating that the GPU was heavily engaged in rendering or compositing tasks during this period.

![image](https://github.com/user-attachments/assets/6e52e12f-fdad-4696-ac1f-77712dd6dd75)

Upon examining the fourth critical time frame the task lasted for 13.77 seconds, leading to a substantial lag and eventual freezing of the application. The detailed analysis of this task reveals insights into its origin and impact:

![image](https://github.com/user-attachments/assets/72aeef75-e689-4cd6-98d7-26359bab89ac)

Detailed Analysis of Long JavaScript Task:

1. Long Task Summary:

- Warning: Long task took 13.77 s.
- Total Time: 13.77 s
- Self Time: 9.41 ms

![image](https://github.com/user-attachments/assets/79584362-9d2f-4a9c-bb58-22ddb2e40205)

2. Event Level:

- Event Type: click
- Total Time: 13.76 s
- Self Time: 60 μs
- Aggregated Time:
   - Scripting (self): 0 ms
   - Scripting (children): 13,454 ms
   - System: 306 ms
   - Total: 13,760 ms

![image](https://github.com/user-attachments/assets/54fec37e-1fe2-4dfd-b047-ab9894e229de)

> The long task was triggered by a click event, consuming a substantial amount of time in scripting, specifically within its children functions.

3. Function Call Level:

- Function: `(anonymous)` `@` `game.js:676:46`
- Total Time: 13.76 s
- Self Time: 14 μs
- Aggregated Time:
   - Scripting (self): 0 ms
   - Scripting (children): 13,454 ms
   - System: 306 ms
   - Total: 13,760 ms 

![image](https://github.com/user-attachments/assets/a8bc4557-707f-4275-b3cb-a2145fd93a75)

> The function at `game.js:676:46` was responsible for the majority of the time, indicating that it contains the core logic causing the delay.

4. hideAvailablePositions Function:

- Function: `hideAvailablePositions` `@` `game.js:1255:25`
- Total Time: 13.76 s
- Self Time: 0 ms
- Aggregated Time:
   - Scripting (children): 13,453 ms
   - System: 305 ms
   - Total: 13,759 ms

![image](https://github.com/user-attachments/assets/1bec9b3c-e97c-4fac-817f-c300ba764258)

> This function, `hideAvailablePositions`, primarily contributed to the delay by delegating extensive tasks to its child functions.

5. _restorePieces Function:

- Function: `_restorePieces` `@` `game.js:1119:17`
- Total Time: 13.76 s
- Self Time: 85.21 ms
- Aggregated Time:
   - Scripting (self): 85 ms
   - Scripting (children): 13,368 ms
   - System: 305 ms
   - Total: 13,759 ms

![image](https://github.com/user-attachments/assets/e2bf6709-2af0-4a74-890e-3bc04e9d8382)

> The `_restorePieces` function, which handles significant processing, was one of the major contributors to the task's total execution time.

6. drawPiece Function:

- Function: `drawPiece` `@` `game.js:1170:12`
- Total Time: 383.74 ms
- Self Time: 3.72 ms
- Aggregated Time:
   - Scripting (self): 4 ms
   - Scripting (children): 379 ms
   - System: 1 ms
   - Total: 384 ms

![image](https://github.com/user-attachments/assets/ae74e248-831d-4a10-b105-016111743b45)

> The `drawPiece` function, while not the main contributor, still took a significant amount of time due to processing of drawing operations.

7. restore Function:

- Function: `restore`
- Total Time: 362.65 ms
- Self Time: 362.65 ms

> The `restore` function was responsible for a substantial amount of the time, suggesting it is a critical point of performance issues.

8. CPP GC (Garbage Collection):

- Total Time: 31 μs
- Self Time: 1 μs

> Garbage Collection (GC) in C++ had minimal impact compared to the JavaScript tasks, indicating that the primary performance issues are related to the JavaScript execution.

The long JavaScript task that caused the game to freeze for 13.77 seconds was primarily due to extensive processing within functions like `hideAvailablePositions`, `_restorePieces`, and `drawPiece`. The performance issue appears to be rooted in inefficient handling of rendering and state management tasks.

### Key Findings:

- **`hideAvailablePositions` Function:** This function consistently appeared as a major contributor to the lag. It triggers extensive processing and delegations to other functions, resulting in high execution times.
- **`_restorePieces` Function:** This function is involved in substantial processing and is a key factor in the observed long task durations. Its inefficiencies have a direct impact on performance.
- **`drawPiece` Function:** Although not the primary cause, this function contributes to the rendering delays. The time spent in drawing operations adds up to the overall lag.

@tedhyu

**Comment by TKanX** [comment]
### Optimized piece rendering and caching

https://github.com/tridecco/game-client-web/commit/16aed06d935f13b4f4d66df283efa8b7f67c9a64

- Refactored `_restorePieces` to optionally use a cache (piecesCanvas) for improved performance.
- Updated `resizeCanvas` to handle resizing of piecesCanvas and call `_restorePieces` with caching disabled for initial rendering.
- Modified `drawPiece` to draw pieces on piecesCanvas first, then copy to the main canvas, reducing the need for frequent redraws.

Changes:
- Added `useCache` parameter to `_restorePieces` method for conditional caching.
- Introduced `piecesCanvas` and `piecesCtx` for optimized piece rendering.
- Adjusted `drawPiece` method to use caching canvas before drawing on the main canvas.

**Comment by TKanX** [comment]
Performance and rendering issues have been successfully resolved. After optimizing the piece rendering process and introducing a caching mechanism, the performance has significantly improved. I re-recorded the performance metrics, and there are no more signs of lag or unresponsiveness. The memory usage is now between 25-40 MB.

![image](https://github.com/user-attachments/assets/137fc485-a01f-4c3f-81f5-7cd97d0906fa)

@tedhyu
