### ISSUE TITLE
Scoring of the game is not correct for 2nd place

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#28]
![tridecco score](https://github.com/user-attachments/assets/2e56047f-ff1f-432b-8613-e6b81812a256)

In a 3 player game, for the 1st and 3rd round, the score seems to be incorrect as the 2nd place player got 1 points and 3rd place player got 2 points.  The 1st place player correctly got 3 points.

In the 2nd round, all scores are correct.

There seems to be some issues with who took 3rd place or 2nd place in a three player game after each round.

**Comment by TKanX** [comment]
Hi Dr. Yu,

I’ve identified the issue you mentioned. In a 3-player game, during the 1st and 3rd rounds, the score seems incorrect as the 2nd place player received 1 point and the 3rd place player received 2 points, while the 1st place player correctly got 3 points. However, all the scores in the 2nd round are correct. It looks like there's an issue with determining who took 2nd and 3rd place after each round in a 3-player game.

Today, I worked for about 10 hours and implemented several new features:

- Added the ability to display statistics and scores after each round.
- Fixed the issue with game hints being blocked by other elements and enabled click-through functionality.
- Added white shadow highlights for better visibility and further optimized the UI and rendering performance.
- Improved the efficiency of click events.
- Implemented player rotation according to the color order in the game rules.

**Comment by tedhyu** [comment]
That’s amazing Tony. Good job!

**Comment by TKanX** [comment]
### Ensured correct player turn order and final ranking

https://github.com/tridecco/game-server/commit/915e6d94a811b6289117597a1b3552bb85d881fe

- Ensure `endPlayerRound` is called in the correct sequence based on player completion.
- Fix issue with final ranking of the last two players, ensuring proper score calculation and ranking.
