### ISSUE TITLE
Optimize Piece Display – Show Quantity for Multiple Same Pieces

### ISSUE THREAD

**Issue by TKanX** [tridecco/game-client-web#33]
### Description:

When a player has multiple pieces of the same type, instead of displaying each individual piece, the UI should consolidate them into a single display with a number representing the quantity. This applies when pieces are shown during moves and trades to prevent clutter and improve clarity.

### Requirements:

- [x] When a player has multiple pieces of the same type, display the piece once with a number indicating the quantity.
- [x] Ensure this optimized display applies both when pieces are shown during gameplay (e.g., when making a move) and during trade actions.
- [x] The number should update dynamically as the player adds or removes pieces.
- [x] The UI should prevent an infinite display of pieces when a player has many of the same type, keeping the interface clean and readable.

**Comment by TKanX** [comment]
### Consolidated identical pieces into a single element with a count badge

https://github.com/tridecco/game-client-web/commit/943f86d8a9be495ea745a4525db4f65594045a73

- Consolidated identical pieces into a single element with a count badge.
- Updated the `showPieceSelection` method to create a map of piece counts.
- Displayed the count of each piece in the top-left corner of the piece element.
- Ensured the click handler worked correctly with the new structure.

**Comment by TKanX** [comment]
### Consolidated identical pieces into a single element with a count badge in showTrade

https://github.com/tridecco/game-client-web/commit/53e57a1c72d00d407f62e89cfe2d45b4846e41fa

- Consolidated identical pieces into a single element with a count badge.
- Updated the `showTrade` method to create a map of piece counts.
- Displayed the count of each piece in the top-left corner of the piece element.
- Ensured the click handler worked correctly with the new structure.

**Comment by TKanX** [comment]
![Image](https://github.com/user-attachments/assets/a4e04830-66cb-4b2f-a4ba-4828f163ad2b)
![Image](https://github.com/user-attachments/assets/5deab82d-6746-4ab3-99e7-3cc0a4d568e9)

@tedhyu

**Comment by tedhyu** [comment]
This looks great!
