### ISSUE TITLE
Add a logout button

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#36]
A logout button should be useful.

**Comment by TKanX** [comment]
> A logout button should be useful.

Hi Dr. Yu,

This feature has been added in the previous [v0.1.0-beta](https://github.com/tridecco/game-client-web/releases/tag/v0.1.0-beta) version, detailed commit: https://github.com/tridecco/game-client-web/commit/e37350153dc0ed8196d23bf66c7bcc57ef289e2b. Do you have any other requirements?

@tedhyu
