### ISSUE TITLE
Piece Selection Obstructing Board on Mobile

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#55]
The tile selection on the mobile game is blocking the board, so the area that it is on cannot be placed with a tile.

Perhaps, move the tile selection to the bottom.

See picture
![error](https://github.com/user-attachments/assets/0a025553-931e-4993-b078-10528553f1d7)

**Comment by TKanX** [comment]
There are still occlusion issues when testing the new layout, which leads to more complex logic and problems. Closing this issue for now. This feature will be implemented in the next major version by rewriting the custom layout.
