### ISSUE TITLE
Add White Highlight Around the Last Piece Played

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#56]
Add highlight to the last tile selected.  While playing the game, there was a suggestion to highlight the last piece played (either by the opponent or the player) so the player can get a sense of where to play.  See suggested to add highlight of white around the last piece.

I'm not sure if this is something that needs to go in the new version or the old version. 

![highlight_example](https://github.com/user-attachments/assets/ead69e86-ba72-4d48-94f4-829e53abda85)

**Comment by TKanX** [comment]
Closing this issue for now. Will consider it in a future version as development for the current version is paused.
