### ISSUE TITLE
Points Not Updating Correctly Between Rounds in Two-Player Game

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#57]
For the display of score in two player multi round game, the points are always the current game score and does not include previous game score.  This happens only between round 2 and 3 for multi round game.  

Also, the pieces remaining is a cool idea, and I'm not sure if you want to implement it as a feature later on.

**Comment by TKanX** [comment]
The current logic is to update each player's score after each round to the total score of all previous rounds:

![Uploading 1code.png…]()
![Uploading code.png…]()

**Comment by TKanX** [comment]
The current logic is to update each player's score after each round to the total score of all previous rounds:

![1code](https://github.com/user-attachments/assets/4efc977b-7a6b-470a-a63c-f89cd4520351)
![code](https://github.com/user-attachments/assets/994a12bd-2226-4ba2-a4df-1bd4e9bd86e8)

**Comment by TKanX** [comment]
Hi Dr. Yu,

I tested the game and there were no unexpected results. Can you provide more detailed information?

@tedhyu

**Comment by tedhyu** [comment]
I can show you during break.  I am in the AC quad.  We all saw the error yesterday,, and hopefully I can reproduce it.
