### ISSUE TITLE
Add a Game Rules Page

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#59]
A temporary solution is to add a link to:  https://tridecco.com/instructions

![image_instructions](https://github.com/user-attachments/assets/b9c1aea1-a1fc-49df-9a5b-6b05fd6e6d4b)

**Comment by TKanX** [comment]
### Description:

Create a dedicated page for displaying the game rules to improve user experience and ensure players clearly understand how to play the game.

### Requirements:

- [ ] **Add Temporary Link to Game Rules**: Add a link to the "Game Rules" page in the main navigation or footer that redirects to https://tridecco.com/instructions for the time being.
- [ ] **Create Game Rules Page**: Design and implement a dedicated "Game Rules" page, which will provide detailed instructions for players on how to play the game.

**Comment by TKanX** [comment]
![Image](https://github.com/user-attachments/assets/729df9b5-9237-4488-8331-e76e4b2a68b5)

@tedhyu

**Comment by TKanX** [comment]
### Corrected grammar in instructions page text

https://github.com/tridecco/game-client-web/commit/f6bc940897c466436a454b9e218237981a9a29e4

- Changed "All your game records, including detailed replays, are available on your profile. Use this feature to analyze your strategies and improve your gameplay." to "All of your game records, including detailed replays, are available on your profile. Use this feature to analyze your strategies and improve your gameplay."
