### ISSUE TITLE
Request for Game Logo, Favicon, and Tile Textures

### ISSUE THREAD

**Issue by TKanX** [tridecco/game-client-web#7]
### We need the following graphical assets for the game client:

- [x] 1. **Game Logo:** High-resolution image for use in the main menu and UI elements.
- [x] 2. **Favicon (Ico):** Icon file (.ico) for the browser tab.
- [x] 3. **Tile Textures:** Image files for the game pieces/tiles, covering all types used in the game.

Please provide these assets at your earliest convenience.

**(Please upload (drag and drop) the file directly to this Issue!)**

Thank you!

@tedhyu

**Comment by tedhyu** [comment]
Yes.  Let me get it to you ASAP

**Comment by tedhyu** [comment]
I also attached red, blue, green, and yellow whole gems once the gems are formed.

**Comment by TKanX** [comment]
Hi Dr. Yu, Thank you very much for providing the files.

**Comment by tedhyu** [comment]
Hi Tony:

I have attached the logo and ico file.  Let me know if this works.  Also, if you can be a bit more specific on where the logo file is to be placed, I can try to make it look perfect for the placement.  Like what part of the game will it be at?  

We can try to use this one for now, but I can change it so it looks better later.  Nothing finalized.  Also, if you have any images you want me to create like "You win!"  Or "trade".  Anything in terms of visual that you want me to look over, I can assist and provide image files.

I emailed the ico file to you because github doesn't seem to accept.
![logo_tony](https://github.com/user-attachments/assets/bfc74ae3-43e2-4760-b7eb-094e5f767347)



Thanks for your hard work.

Regards,

Ted

**Comment by TKanX** [comment]
Hi Dr. Yu,

Thank you very much for the files. I will add them as soon as possible!

If you need anything modified, feel free to contact me!

Best regards,

Tony Kan

**Comment by TKanX** [comment]
### Added favicon.ico for better site branding

https://github.com/tridecco/game-client-web/commit/b73ef26c677e132f3821c9141bba51dbbb45bb1b

Added `favicon.ico` to improve site branding and user experience.

**Comment by TKanX** [comment]
### Replaced all logos across the application

https://github.com/tridecco/game-client-web/commit/59c4147a232f851cd9789a134ce0fb9c9a0b6800

- Updated the main header logo to use the new image-based logo instead of the SVG.
- Replaced the SVG logo with the new image-based logo in the login, password reset, register, and two-factor authentication pages.
- Ensured consistent branding by using the `/favicon.ico` image as the logo throughout the application.

**Comment by TKanX** [comment]
### The chess piece files need to be reorganized/edited

**Comment by TKanX** [comment]
1. In [gem-images.zip](https://github.com/user-attachments/files/16438460/gem-images.zip) `blue-green` material is slightly misaligned.
2. The `Tile Textures` files needs to be flipped on the vertical axis.

@tedhyu

**Comment by tedhyu** [comment]
Hi Tony:

1)  The misalignment issue may be an easy fix.  Let me know what it is in more detail.

2)  Here are the flipped gem images
[flipped_tiles.zip](https://github.com/user-attachments/files/16649906/flipped_tiles.zip)

**Comment by TKanX** [comment]
Hi Dr. Yu,

Good morning! Thank you very much for providing the flipped gem images.

I noticed a misalignment between `blue-green.png` and `blue-green-flipped.png`. Could you please take a look?

- `blue-green.png`:
![blue-green](https://github.com/user-attachments/assets/76e9ad07-a3ed-41e6-a187-69d1135a17ae)

- `blue-green-flipped.png`:
![blue-green-flipped](https://github.com/user-attachments/assets/e275e643-5c9e-44ab-91cf-238cf5e76391)

Best regards,

Tony Kan

**Comment by tedhyu** [comment]
OK, I understand the problem.  Sorry about that.  I'll provide a file that's not rotated.

**Comment by tedhyu** [comment]
[gems-fixed.zip](https://github.com/user-attachments/files/16653709/gems-fixed.zip)

Here are the corrected files
